<a href="https://colab.research.google.com/github/Trishalsalian/Machine_Learning/blob/main/lab5decisiontree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:


import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder



print("Upload iris.csv file")
from google.colab import files
uploaded = files.upload()


iris = pd.read_csv("/content/iris (1).csv")

print("\nIRIS Dataset Preview:")
print(iris.head())


X = iris.iloc[:, :-1]
y = iris.iloc[:, -1]


le = LabelEncoder()
y = le.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)


model = DecisionTreeClassifier()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


print("\nIRIS Accuracy:", accuracy_score(y_test, y_pred))
print("\nIRIS Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nUpload drug.csv file")
uploaded = files.upload()


drug = pd.read_csv("/content/drug.csv")

print("\nDrug Dataset Preview:")
print(drug.head())


X = drug.iloc[:, :-1]
y = drug.iloc[:, -1]

le = LabelEncoder()
for column in X.columns:
    if X[column].dtype == 'object':
        X[column] = le.fit_transform(X[column])


y = le.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)


model = DecisionTreeClassifier()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


print("\nDrug Dataset Accuracy:", accuracy_score(y_test, y_pred))
print("\nDrug Dataset Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Upload iris.csv file


Saving iris (1).csv to iris (1) (1).csv

IRIS Dataset Preview:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

IRIS Accuracy: 1.0

IRIS Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Upload drug.csv file


Saving drug.csv to drug (1).csv

Drug Dataset Preview:
   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

Drug Dataset Accuracy: 1.0

Drug Dataset Confusion Matrix:
[[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]
